root = "."
tmp_dir = "tmp"
testdata_dir = "tests"

[build]
  cmd = "go build -o tmp/main ./cmd"
  bin = "tmp/main"

  include_ext = ["go", "tpl", "tmpl", "html", "proto"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]

  delay = 1000
  rerun_delay = 500
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  exclude_regex = ["_test.go"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
